### PR TITLE
fix submission guide link

### PR DESCRIPTION
**Pull request by sh-dave**

### CODE REVIEW

**Comment by yochaigal** [comment]
The link does not require an .md at the end. There is something else going on. I'll look into it!

**Comment by yochaigal** [comment]
The link works fine as it is, would you mind explaining what your experience is like?
Thanks!

**Comment by sh-dave** [comment]
Clicking the link results in a 404. This is with firefox + chromium on debian 11,  and also my mobile phone.

**Comment by yochaigal** [comment]
Not for me. Tried on Chrome and Firefox for Linux, and Chrome for Windows (on a remote PC at a different location). Also Chrome on Android. Is it possible there's something up with your DNS?

This is the link in question, correct:
https://cairnrpg.com/submissions/submission-guide

**Comment by sh-dave** [comment]
No this link works fine, it's not working when i browse the sources here in github.

**Comment by yochaigal** [comment]
Ah. Yes that will not work without the *.md but it isn't standard practice, and I would prefer we fall back on non-md links because folks will copy the link from the web more often. I also often move stuff, and then redirect to old URLs without using the md extension.

My assumption is that this is standard practice - I use plenty of relative links (e.g. /cairn-srd) that won't make sense on the github code view online.

**Pull request closed without merging**
