### PR TITLE
[Belarusian localization] Translate introduction and some of the tables

### PR DESCRIPTION
**Pull request by makouchyk**
Translate first ~400 lines to Belarusian

### CODE REVIEW

**Comment by yochaigal** [comment]
This is wonderful! Wouldn't you rather fork the website, though? Then I can just link to be.cairnrpg.com?

**Comment by makouchyk** [comment]
@yochaigal thanks for quick response! I'll try to do it, give me a minute.

**Comment by makouchyk** [comment]
I have renamed the repo, merged my changes into the `cairn-srd.md`, and enabled github pages. But I receive an error when trying to setup the domain. Do I need to do after you've setup the subdomain with your DNS provider?
Screenshot from 2024-02-11 17-40-25

**Comment by yochaigal** [comment]
Yes I need the GitHub pages URL, for example makouchyk.github.io. also be sure to enable SSL!

**Comment by makouchyk** [comment]
I'm not familiar with github pages, but it looks like the site got deployed to https://makouchyk.github.io/cairn-be/

**Comment by yochaigal** [comment]
Yes, that's working! Just make sure you enable SSL.

**Comment by makouchyk** [comment]
Screenshot from 2024-02-11 18-05-07
I think it works now. Thank you!
I'll close the pr now.

**Pull request closed without merging**
