### PR TITLE
fix spelling 

### PR DESCRIPTION
**Pull request by nmeier**
Quick spellcheck run

(Disclaimer: I'm not sure about american e vs british en…glish at times)

### CODE REVIEW

**Comment by yochaigal** [comment]
Hello!
I'm actually not taking ANY PRs for stuff in WIP... because it's WIP and has a whole separate process (as it involves other people). I do take 2e feedback through the appropriate [form](tinyurl.com/2e-feedback) however. If you could change this PR to exclude changes to the WIP section, I'll merge it.

Thanks!

**Comment by nmeier** [comment]
np, taken out /wip

**Comment by nmeier** [comment]
2e feedback seems to be focused on players' guide. There's no page number for the warden's guide.

If you want to check spelling for wip I'll just leave the patch for /wip here- for your perusal

[wip_spellcheck_patch.patch](https://github.com/yochaigal/cairn/files/14217373/wip_spellcheck_patch.patch)

**Comment by yochaigal** [comment]
Yeah, most of what is in the Warden's Guide does not in fact appear in /WIP. That is all old stuff! We are not taking feedback for the Warden's Guide at this time.

**Pull request merged**
